### ISSUE TITLE
Cannot read properties in p5Fbo.js

### ISSUE THREAD

**Issue by kpvvong** [aferriss/p5Fbo#2]
I put the example file in a blank project, is something that was missed?

```
🌸 p5.js says: An error with message "Cannot read properties of undefined (reading 'TEXTURE_2D')" occured inside the p5js library when Texture was called (on line 18 in p5Fbo.js [http://localhost:8080/p5Fbo.js:18:18])

If not stated otherwise, it might be an issue with the arguments passed to Texture. (http://p5js.org/reference/#/p5/Texture)
```

**Comment by aferriss** [comment]
You need to use a master build of p5.js, since this depends on some very recent changes. You can grab a pre-built one from here:
https://github.com/aferriss/p5Fbo/blob/master/p5.min.js

Let me know if that doesn't fix the issue.
